<a href="https://colab.research.google.com/github/eliot28/desafioLatam/blob/main/Tutoria_3_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# @title Texto de título predeterminado

## lista
frutas = ['manzana','banana','uva','fresa']<

## diccionario
amigos = {'Juan':'Bogota',
          'Maria':'Medellin',
          'Luis':'Cali',
          'Ana':'Barranquilla'}

## para agregar elemtos a listas
frutas.append('pera')

## para agregar elemtos a diccionario
amigos['Raul'] = 'Caracas'

print(frutas)

print('Lista de fruta favoritas:')
for x in frutas:
  print('-',x)


['manzana', 'banana', 'uva', 'fresa', 'pera']
Lista de fruta favoritas:
- manzana
- banana
- uva
- fresa
- pera


In [2]:
amigos.items()

dict_items([('Juan', 'Bogota'), ('Maria', 'Medellin'), ('Luis', 'Cali'), ('Ana', 'Barranquilla'), ('Raul', 'Caracas')])

In [3]:
type(amigos)

dict

In [5]:
type(amigos.items()) ## se utiliza para transformar dict a tuplas para poder recorrer el diccionario

dict_items

In [ ]:
for amigo, ciudad in amigos.items():
  print(f' {amigo} vive en {ciudad}')

 Juan vive en Bogota
 Maria vive en Medellin
 Luis vive en Cali
 Ana vive en Barranquilla
 Raul vive en Caracas


In [6]:
#amigos = {'Juan':133:'Moneda 5000','Maria':24,'Luis':30,'Ana':25,'Jose':30}
amigos2 = ('Juan':1,'Moneda 5000','Maria':24,'Luis':30,'Ana':25,'Jose':30) ## las tuplas no soportan los :
print(amigos2)

SyntaxError: invalid syntax (<ipython-input-6-8ac7268b9f01>, line 2)

In [10]:
amigos3 ={'Juan':[1,2,3],'Maria':24,'Luis':30,'Ana':25,'Jose':30}
print(amigos3)
print(amigos3['Juan'])
print(amigos3['Juan'][2])

{'Juan': [1, 2, 3], 'Maria': 24, 'Luis': 30, 'Ana': 25, 'Jose': 30}
[1, 2, 3]
3


In [ ]:
amigos3 ={'rut':[1111111],'Maria':24,'Luis':30,'Ana':25,'Jose':30}
print(amigos3)
print(amigos3['Juan'])
print(amigos3['Juan'][2])

## los diccionario te permiten guardar listas solo en el segundo argumento




In [11]:
## asi no
amigos3 ={[1,2,3,4]:20,'Maria':24,'Luis':30,'Ana':25,'Jose':30}
print(amigos3)

TypeError: unhashable type: 'list'

In [16]:
# @title Texto de título predeterminado
#frutas = ['manzana','banana','uva','fresa']
amigos = {'Juan':30,'Maria':24,'Luis':30,'Ana':25,'Jose':30}

# quitar elementos de una lista
frutas.remove('fresa')

# quitar elementos de un diccionario esta el del
del amigos['Jose']



frutas = ['manzana','banana','uva','fresa','mango','piña','maracuya']
#filtro lista
frutas_filtradas = [fruta
                    for fruta in frutas
                    if fruta.lower().startswith('m')]

for fruta in frutas_filtradas:
  print('-',fruta)

print('')

## recorro todos los items del diccionario
for amigo, edad in amigos.items():
    #print(amigo)
    if edad == 30:
      print('-',amigo)


- manzana
- mango
- maracuya

Juan
- Juan
Maria
Luis
- Luis
Ana


In [17]:
type(frutas_filtradas)

list

In [27]:
frutas = ['manzana','banana','uva','fresa','mango','piña','maracuya']
# normal
print(frutas)

## orden de lista ascendente
frutas.sort()
print(frutas)

## orden de lista descendente
frutas.sort(reverse=True)
print(frutas)

['manzana', 'banana', 'uva', 'fresa', 'mango', 'piña', 'maracuya']
['banana', 'fresa', 'mango', 'manzana', 'maracuya', 'piña', 'uva']
['uva', 'piña', 'maracuya', 'manzana', 'mango', 'fresa', 'banana']


In [28]:
numeros = [2,5,1,-3,9,4]
print(numeros)

## ascendente
numeros.sort()
print(numeros)

## desc
numeros.sort(reverse=True)
print(numeros)

[2, 5, 1, -3, 9, 4]
[-3, 1, 2, 4, 5, 9]
[9, 5, 4, 2, 1, -3]


In [34]:
## desde listas a diccionarios
nombre = ['Juan','Maria','Pedro']
edad = [20,34,56]
diccionario_nombre=dict(zip(nombre,edad))
print(diccionario_nombre)

{'Juan': 20, 'Maria': 34, 'Pedro': 56}


In [36]:
## desde diccionarios a listas
nombre_lista = list(diccionario_nombre.keys()) ## nombre_lista = list(diccionario_nombre) es lo mismo
edad_lista = list(diccionario_nombre.values())

print(nombre_lista)
print(edad_lista)

['Juan', 'Maria', 'Pedro']
[20, 34, 56]


In [ ]:
amigos_ordenados = dict(sorted(amigos.items()))
print(amigos)
print(amigos_ordenados)

print(amigos.items())
print(sorted(amigos.items()))


#for amigo, edad in amigos_ordenados.items():
#  print(f'Mi amigo {amigo} tiene {edad} años')

{'Juan': 30, 'Maria': 24, 'Luis': 30, 'Ana': 25}
{'Ana': 25, 'Juan': 30, 'Luis': 30, 'Maria': 24}
dict_items([('Juan', 30), ('Maria', 24), ('Luis', 30), ('Ana', 25)])
[('Ana', 25), ('Juan', 30), ('Luis', 30), ('Maria', 24)]


In [ ]:
a = ("b", "g", "a", "d", "f", "c", "h", "e")
x = sorted(a)
print(x)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']


In [ ]:
a = [1,5,3,-1,4]
x = sorted(a, reverse=True)
print(x)

[5, 4, 3, 1, -1]


In [ ]:
nombres = ['Juan', 'María', 'Pedro']
edades = [25, 30, 35]

# Usar la función zip para combinar las listas en una lista de tuplas
datos_personales = zip(nombres, edades)


In [38]:
## como instalar numpy
## pip install numpy // para instalar

import numpy as np

lista = [0,1,2,3,4]
my_array = np.array(lista)

print(lista)
print(my_array)

[0, 1, 2, 3, 4]
[0 1 2 3 4]


In [37]:
import numpy as np
np.__version__ ## para ver la versión

'1.25.2'

In [39]:
lista*2

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

In [45]:
lista*-1

[]

In [46]:
my_array*2

array([0, 2, 4, 6, 8])

In [47]:
lista1 = [1,2,3]
lista2 = [10,20,30]
lista3 = [100,200,3000]

array1 = np.array(lista1)
array2 = np.array(lista2)
array3 = np.array(lista3)

In [48]:
lista1 + lista2 + lista3

[1, 2, 3, 10, 20, 30, 100, 200, 3000]

In [49]:
lista1 - lista2 # no se puede

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [50]:
lista1 * lista2 # no se puede

TypeError: can't multiply sequence by non-int of type 'list'

In [51]:
array1 + array2 + array3

array([ 111,  222, 3033])

In [52]:
array1*array2

array([10, 40, 90])

In [53]:
array2 - array1

array([ 9, 18, 27])

In [57]:
lista_texto = ['a','b','c']
lista_texto2 = [1,2,3]

array_texto = np.array(lista_texto)
array_texto2 = np.array(lista_texto2)

print(array_texto*array_texto2)  ## si es texto no numero no me va a funcionar

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U1'), dtype('int64')) -> None

In [58]:
lista_num = [1,6,3,8,2,9,10]

arr = np.array(lista_num)
## filtros
arr[arr >= 8]

array([ 8,  9, 10])

In [62]:
## logica and

arr[np.logical_and(arr > 5, arr < 10)]

array([6, 8, 9])

In [60]:
## logica or
arr[np.logical_or(arr <= 3, arr > 8)]

array([ 1,  3,  2,  9, 10])

In [69]:
personas = ['Claudia','Marcela','Luis','Antonio','Laura','Jose','Pedro']
edades = np.array([5,12,17,3,8,41,24])

print(edades.argmax()) ## el lugar donde esta el maximo valor
print(edades[edades.argmax()])
print('')
print(edades.argmin())
print(edades[edades.argmin()])

5
41

3
3


In [70]:
print(edades[edades>18]) ## todas las edades mayores a 18

[41 24]


In [71]:
print(edades[edades>18].shape) ## cuenta cuantos valores cumplen con la logica

(2,)


In [73]:
csv = np.loadtxt('alcohol_cerveza.csv',delimiter=',',encoding='utf-8')
print(csv)

#'ascii'

print(csv.shape)

[0.   5.06 4.29 ... 4.68 5.12 4.92]
(1001,)
